= Nog een ronde dan maar!
Tymo Ooijevaar
v0.1, 12-03-2024

:Title: Nog een ronde dan maar!
:Template: index

:toc:

== Samenvatting

== 1. Inleiding

Wellicht ken je dat gevoel wel: een vriend die in een online spel, candy-crush
of op een level in een game als Hitman een veel hogere score en een betere
tijd heeft neergezet dan jij zelf niet voor mogelijk hield. Je voelt dat
gevoel dan opkomen: dat gevoel wat zegt dat je dat daar niet bij wilt laten
zitten en je net zo lang wilt blijven spelen totdat je die score van je vriend
hebt ingehaald en hem hebt verslagen. Dit gevoel in de motivatie om een bekend
videospel langer en vaker te willen spelen om deze of andere persoonlijk
gestelde doelen te behalen is een relatief nieuw fenomeen (bronvermelding) wat
met de opkomst van speedrunning in kracht en invloed op videospel spelende
mensen (gamers) is toegenomen (bronvermelding). Wat voor een invloed kan het
speedrunnen van een videospel hebben op de motivatie om dit spel telkens
opnieuw te blijven spelen?
